# Aether artifact version
aether_version = 1.5.0

org.gradle.jvmargs = -Xmx2g -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8

# Mod properties
maven_group = dev.aether
archives_base_name = aether

# Fabric properties
minecraft_version = 26.1.2
loader_version = 0.19.3
fabric_version = 0.152.1+26.1.2
